### ISSUE TITLE
Sample doesn't even run. Don't bother.

### ISSUE THREAD

**Issue by mihaimorcov** [jszczygiel/AndroidYoutubeOverlay#4]
Don't waste your time trying to test this - the project is probably outdated.

```
com.wroclawstudio.example E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.wroclawstudio.example, PID: 2927
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wroclawstudio.example/com.wroclawstudio.example.ScrollExampleActivity}: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.youtube.api.service.START VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} }
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
at android.app.ActivityThread.access$1100(ActivityThread.java:
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.youtube.api.service.START VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} }
```

**Comment by jszczygiel** [comment]
Well, 

yes it is outdated and haven't been maintained in a while. I will look into issue in spare moment. Thanks for bug report.
